### ISSUE TITLE
unknown bug

### ISSUE THREAD

**Issue by codefather-labs** [long2ice/aerich#4]
```
local_config = {
    "connections": {
        Database.translate_service_db.name: 'postgres://translate_service:'
                                            'translate_service@0.0.0.0:54320/'
                                            'translate_service_db'
    },
    "apps": {
        "translator": {
            "models": models,
            "default_connection": Database.translate_service_db.name
        },
    },
}
```

`aerich init -t services.translator.utils.local_config`

Success create migrate location ./migrations
Success generate config file aerich.ini

`aerich init-db`
Success create app migrate location ./migrations/models
Traceback (most recent call last):
  File "/home/codefather/Projects/my_project/venv/bin/aerich", line 8, in <module>
    sys.exit(main())
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/aerich/cli.py", line 213, in main
    cli(_anyio_backend="asyncio")
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 799, in __call__
    return anyio.run(self._main, main, args, kwargs, backend=_anyio_backend)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/anyio/__init__.py", line 68, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 97, in run
    raise exception
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 67, in wrapper
    retval = await func(*args)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 802, in _main
    return await main(*args, **kwargs)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 748, in main
    rv = await self.invoke(ctx)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 1175, in invoke
    return await _process_result(await sub_ctx.command.invoke(sub_ctx))
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 994, in invoke
    return await ctx.invoke(self.callback, **ctx.params)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/asyncclick/core.py", line 588, in invoke
    rv = await rv
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/aerich/cli.py", line 202, in init_db
    Migrate.write_old_models(config, app, location)
  File "/home/codefather/Projects/my_project/venv/lib/python3.8/site-packages/aerich/migrate.py", line 183, in write_old_models
    models = config.get("apps").get(app).get("models")
AttributeError: 'NoneType' object has no attribute 'get'

postgres9.5

**Comment by long2ice** [comment]
Because your Tortoise-ORM app is not default app ``models``, so you need specify ``--app``, like ``aerich --app translator init-db``

**Comment by codefather-labs** [comment]
looks like done
thanks!

**Comment by codefather-labs** [comment]
got new problem

```
aerich --app translator init -t services.translator.utils.local_config
aerich --app translator init-db
```

first command looking good. i see valid result. `aerich --app translator init-db` returns a 

> Success generate schema

 but in next step - `aerich migrate --name drop_column` it returs to me this response 

> Error: You must exec init-db first

and --app translator prefix do not help this time :(

**Comment by codefather-labs** [comment]
hmm, but i see tables in my postgres...

**Comment by long2ice** [comment]
update aerich from github now,then you can real error msg.

**Comment by codefather-labs** [comment]
dont work in version 0.1.7

**Comment by long2ice** [comment]
what error log?

**Comment by codefather-labs** [comment]
#https://github.com/long2ice/aerich/issues/6
